# Generated by Django 5.2.8 on 2025-11-25 19:10

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AITrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp_sec', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='временная метка (сек)')),
                ('trigger_source', models.CharField(choices=[('whisper_profanity', 'Whisper - Мат'), ('whisper_brand', 'Whisper - Бренд'), ('falconsai_nsfw', 'Falconsai - NSFW'), ('violence_detector', 'Детектор насилия'), ('yolo_object', 'YOLO - Объект'), ('easyocr_text', 'EasyOCR - Текст')], max_length=50, verbose_name='источник триггера')),
                ('confidence', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='уверенность')),
                ('data', models.JSONField(verbose_name='данные')),
                ('status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('processed', 'Обработан оператором')], db_index=True, default='pending', max_length=20, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'AI триггер',
                'verbose_name_plural': 'AI триггеры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('running', 'Выполняется'), ('completed', 'Завершено'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=20, verbose_name='статус')),
                ('current_task', models.CharField(blank=True, max_length=100, verbose_name='текущая задача')),
                ('progress', models.IntegerField(default=0, verbose_name='прогресс')),
                ('error_message', models.TextField(blank=True, verbose_name='сообщение об ошибке')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='время начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='время завершения')),
                ('processing_time_seconds', models.IntegerField(default=0, verbose_name='время обработки (сек)')),
                ('api_calls_count', models.IntegerField(default=0, verbose_name='количество вызовов API')),
                ('cost_estimate', models.DecimalField(decimal_places=6, default=Decimal('0.0'), max_digits=10, verbose_name='оценка стоимости')),
            ],
            options={
                'verbose_name': 'выполнение пайплайна',
                'verbose_name_plural': 'выполнения пайплайнов',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('in_progress', 'В работе'), ('completed', 'Завершено')], db_index=True, default='pending', max_length=20, verbose_name='статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='время начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='время завершения')),
                ('total_processing_time', models.IntegerField(default=0, verbose_name='общее время обработки (сек)')),
            ],
            options={
                'verbose_name': 'задача на верификацию',
                'verbose_name_plural': 'задачи на верификацию',
                'ordering': ['-id'],
            },
        ),
    ]
