# Generated by Django 5.2.8 on 2025-11-25 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_pipeline', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitrigger',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_triggers', to='projects.video', verbose_name='видео'),
        ),
        migrations.AddField(
            model_name='pipelineexecution',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_execution', to='projects.video', verbose_name='видео'),
        ),
    ]
