# Generated by Django 5.2.8 on 2025-11-25 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_pipeline', '0002_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationtask',
            name='operator',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'OPERATOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='оператор'),
        ),
        migrations.AddField(
            model_name='verificationtask',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_task', to='projects.video', verbose_name='видео'),
        ),
    ]
