# Generated by Django 5.2.8 on 2025-11-25 19:10

import projects.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255, verbose_name='оригинальное название')),
                ('video_file', models.FileField(blank=True, null=True, upload_to=projects.models.get_video_upload_path, verbose_name='файл видео')),
                ('video_url', models.URLField(blank=True, max_length=2000, null=True, verbose_name='URL видео')),
                ('duration', models.IntegerField(default=0, verbose_name='длительность (секунды)')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='размер файла (байты)')),
                ('status', models.CharField(choices=[('UPLOADED', 'Загружено'), ('PROCESSING', 'Обработка AI'), ('VERIFICATION', 'На верификации'), ('COMPLETED', 'Готово'), ('FAILED', 'Ошибка обработки')], db_index=True, default='UPLOADED', max_length=20, verbose_name='статус')),
                ('status_message', models.TextField(blank=True, verbose_name='сообщение о статусе')),
                ('ai_report', models.JSONField(blank=True, null=True, verbose_name='отчет AI')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='дата обработки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'видео',
                'verbose_name_plural': 'видео',
                'ordering': ['-created_at'],
            },
        ),
    ]
