# Generated by Django 5.2.8 on 2025-11-25 19:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time_sec', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='время начала (сек)')),
                ('final_label', models.CharField(choices=[('ok', 'OK'), ('ok_false', 'OK (ложное срабатывание)'), ('reklama_brand', 'Реклама (бренд)'), ('mat_speech', 'Мат (речь)'), ('nsfw_18', 'Порнография (18+)'), ('violence_18', 'Насилие (18+)')], db_index=True, max_length=50, verbose_name='финальная метка')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('ai_trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator_decisions', to='ai_pipeline.aitrigger', verbose_name='AI триггер')),
            ],
            options={
                'verbose_name': 'метка оператора',
                'verbose_name_plural': 'метки операторов',
                'ordering': ['-created_at'],
            },
        ),
    ]
