# Generated by Django 5.2.8 on 2025-11-25 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorlabel',
            name='operator',
            field=models.ForeignKey(limit_choices_to={'role': 'OPERATOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_labels', to=settings.AUTH_USER_MODEL, verbose_name='оператор'),
        ),
        migrations.AddField(
            model_name='operatorlabel',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_labels', to='projects.video', verbose_name='видео'),
        ),
    ]
